openapi: 3.0.3
info:
  title: Choreo Samples - Review Management - REST API
  description: >-
    This is a API specification for a conference and review management system.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:5000
tags:
  - name: reviews
    description: API to retrieve reviews for conferences
paths:
  /conferences:
    summary: List all conferences
    get:
      summary: List all conferences
      operationId: ListAllConferences
      tags:
        - conferences
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConferenceArray"
  /conferences/{id}:
    summary: Get conference by ID
    get:
      tags:
        - conferences
      summary: Get conference by ID
      operationId: GetConferenceById
      parameters:
        - name: id
          in: path
          description: id of conference to return
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Conference"
        "404":
          description: id not found
  /conferences/{id}/reviews:
    summary: List all reviews for a conference    
    get:
      summary: List all reviews for a conference
      operationId: ListAllReviewsForConference
      tags:
        - reviews
      parameters:
        - name: id
          in: path
          description: id of conference to return reviews for
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReviewArray"

components:
  schemas:
    Conference:
      type: object
      properties:
        id:
          type: integer
          description: The conference ID
        name:
          type: string
          description: The conference name
        description:
          type: string
          description: The conference description
        start_date:
          type: string
          format: date
          description: The conference start date
        end_date:
          type: string
          format: date
          description: The conference end date
        location:
          type: string
          description: The conference location
        speakers:
          type: array
          description: List of speakers
          items:
            type: string
        website:
          type: string
          description: The conference website
        overall_rating:
          type: number
          description: The conference overall rating
    ConferenceArray:
      type: array
      items:
        $ref: '#/components/schemas/Conference'
    Review:
      type: object
      properties:
        id:
          type: integer
          description: The review ID
        user_id:
          type: integer
          description: The user ID
        conference_id:
          type: integer
          description: The conference ID
        description:
          type: string
          description: The review description
        rating:
          type: number
          description: The review rating
    ReviewArray:
      type: array
      items:
        $ref: '#/components/schemas/Review'