apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: Review Management
      port: 5000
      type: REST
      networkVisibility: Public
      context: /
      schemaFilePath: openapi.yaml
  outbound:
    serviceReferences:
    - name: choreo:///pixelpioneer/summit-score/mvkdbw/2f6ac/v1.0/PUBLIC
      connectionConfig: 01ef03e8-54b1-1a90-9efc-48548b3eff8e
      env:
      - from: ServiceURL
        to: NEXT_PUBLIC_BASE_URL